# Generated by Django 4.1.2 on 2022-12-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Cityweather',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
