# Generated by Django 4.1.2 on 2023-01-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
