# Generated by Django 4.1.2 on 2023-01-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_detail_name_alter_detail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
