# Generated by Django 4.1.2 on 2023-01-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_detail_name_alter_detail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
